name: CinePro
services:
  backend:
    build: .
    ports:
      - '3010:3010'
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
